name = "Durbyn"
uuid = "40b042de-e8ce-4d84-a20a-09ad0ba5d568"
authors = ["Resul Akay <resul.akay@taf-society.org> and contributors"]
version = "0.0.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataStructures = "0.18.22"
Distributions = "0.25.120"
LinearAlgebra = "1.11.0"
Plots = "1.40.13"
Polynomials = "4.0.19"
Statistics = "1.11.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
